### ISSUE TITLE
Postgres and 3 Replicas

### ISSUE THREAD

**Issue by dondragon2** [camunda-community-hub/camunda-helm#25] opened 2021-11-09 23:47 UTC
I have a deployment with 3 replicas but I notice that every time I start the deployment with more than 1 replicas I am unable to login. But If I start with 1 then it is fine. Below are the values that I am using.

```
# Default values for camunda-bpm-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

general:
  debug: false
  replicaCount: 3

image:
  repository: camunda/camunda-bpm-platform
  tag: latest

# By default H2 database is used, which is handy for demos and tests,
# however, H2 is not supported in a clustered scenario.
# So for real-world workloads, an external database like PostgreSQL should be used.
database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://postgres-svc.database:5432/process-engine
  credentialsSecretName: camunda-bpm-platform-db-credentials

extraEnvs:
  - name: DB_VALIDATE_ON_BORROW
    value: "true"
  - name: DB_VALIDATION_QUERY
    value: "SELECT 1"

service:
  type: ClusterIP
  port: 8080
  portName: http

metrics:
  enabled: false
  service:
    type: ClusterIP
    port: 9404
    portName: metrics
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/"
      prometheus.io/port: "9404"

# An arbitrary use of livenessProbe could make a lot of service interruption, use it wisely.
livenessProbe:
  enabled: false
  config:
    httpGet:
      path: /camunda/
      port: http
    initialDelaySeconds: 120
    periodSeconds: 60

readinessProbe:
  enabled: true
  config:
    httpGet:
      path: /camunda/
      port: http
    initialDelaySeconds: 120
    periodSeconds: 60
```

Am I missing something?

**Comment by aabouzaid** [comment] 2021-11-10 10:54
Hi @dondragon2 could you please add more details about "I am unable to login"? What is the issue? You don't see the login page or do you have error? or you see the page but nothing happens? or anything else?

**Comment by dondragon2** [comment] 2021-11-10 15:54
Hi @aabouzaid 

All 3 replicas would started properly and are running. I am able to receive the login page for Admin/Cockpit/Tasklist. However, when I enter the username and password (i.e demo/demo) then I receive the Wrong credentials error. and from the inspect Network tab I can see a 401 error. But if I reduce it to 1 replica then I am able to login.

**Comment by aabouzaid** [comment] 2021-11-12 15:19
@dondragon2 I'm not able to reproduce the issue on my machine using the chart `v1.3.0`, docker images `camunda/camunda-bpm-platform:7.16`, `bitnami/postgresql:11.12.0-debian-10-r44`, and Kubernetes `v1.21.1`.

Please provide step by step to reproduce it.

**Comment by aabouzaid** [comment] 2021-12-10 13:58
Closing the issue since it's not reproducible and no updates over the last 30 days.

**Closed by aabouzaid** 2021-12-10 13:58 UTC
